Rework `validateCAARecords` to handle multiple CAA records
willnode/forward-domain pull request #13
Opened 2024-04-16 17:54 UTC by djbe

Fixes #12

2024-04-16 23:50 UTC, willnode commented on src/util.js
> +    if (issueRecords.length == 0 || issueRecords.some(x => x.includes('letsencrypt.org'))) {
```suggestion
    if (issueRecords.length == 0 || issueRecords.some(x => x === "0 issue \"letsencrypt.org\"")) {
```
faster to compute

2024-04-16 23:51 UTC, willnode requested changes
changes requested

2024-04-16 23:55 UTC, willnode commented
Additional context about `issuewild` vs `issue`: We need to match `issue` since this doesn't request a wildcard certificate. Maybe this need to be incorporated into error message.

2024-04-17 00:07 UTC, djbe commented on src/util.js
> +    if (issueRecords.length == 0 || issueRecords.some(x => x.includes('letsencrypt.org'))) {
I mentioned this in the original issue: according to the CAA spec, the quotes are optional (in this case).

I've adapted the check to use a regex if that's allright. It'll correctly handle a case with or without quotes.

2024-04-17 00:14 UTC, willnode approved these changes

2024-04-17 00:14 UTC, merged

2024-04-17 00:14 UTC, djbe commented
Updated the call to the validate function, to use the result and show it to the user.